<?php

/**
 * Implements hook_init().
 */
function course_quiz_init() {
  $node = node_load(arg(1));
  if ($course = course_determine_context('course_quiz', 'quiz', $node->nid)) {
    course_set_context($course);
  }
}

/**
 * Implements hook_course_handlers().
 */
function course_quiz_course_handlers() {
  return array(
    'object' => array(
      'quiz' => array(
        'name' => t('Quiz'),
        'class' => 'CourseObjectQuiz',
        'description' => t('A Quiz course object.'),
      ),
    ),
  );
}

/**
 * Implements hook_quiz_finished().
 *
 * Update the fulfillment record.
 */
function course_quiz_quiz_finished($quiz, $score, $rid) {
  global $user;

  $courseObject = course_get_course_object('course_quiz', 'quiz', $quiz->nid, $user);
  $courseObject->grade($user);
}

/**
 * Implements hook_nodeapi().
 *
 * Update passing grade.
 */
function course_quiz_nodeapi($node, $op, $a3, $a4) {
  if ($node->type == 'quiz') {
    if ($op == 'update') {
      $courseObject = course_get_course_object('course_quiz', 'quiz', $node->nid);
      $courseObject->setOption('passing_grade', $node->pass_rate)->save();
    }
  }
}
