<?php

/**
 * Implementation of hook_init().
 */
function course_book_init() {
  $node = node_load(arg(1));
  $search = $node->book['bid'] ? $node->book['bid'] : $node->nid;
  if ($course = course_determine_context('course_book', 'book', $search)) {
    course_set_context($course);
  }
}

/**
 * Implements hook_course_handlers().
 */
function course_book_course_handlers() {
  return array(
    'object' => array(
      'book' => array(
        'name' => t('Book'),
        'description' => t('A book course object.'),
        'class' => 'CourseObjectNode',
      ),
    ),
  );
}

/**
 * Implementation of hook_nodeapi().
 */
function course_book_nodeapi(&$node, $op, $a3, $a4) {
  if ($op == 'view' && $a4 && $node->type == 'book') {
    global $user;
    $search = $node->book['bid'] ? $node->book['bid'] : $node->nid;
    if ($courseObject = course_get_course_object('course_book', 'book', $search, $user)) {
      $courseObject->getFulfillment()->setComplete()->save();
    }
  }
}
