<?php

/**
 * Implementation of hook_course_object_info().
 */
function course_poll_course_object_info() {
  return array(
    'poll' => array(
      'title' => 'Poll',
      'suggested title' => 'Poll',
      'class' => 'CourseObjectPoll',
      'description' => 'A poll to be used in a course workflow.',
      'graded' => FALSE,
    ),
  );
}

/**
 * Implementation of hook_form_FORMID_alter().
 */
function course_poll_form_poll_view_voting_alter(&$form, &$form_state) {
  $form['vote']['#submit'][] = 'course_poll_fulfill';
}

/**
 * Fulfill the voting requirement.
 */
function course_poll_fulfill(&$form, &$form_state) {
  global $user;

  // Find the course object associated with this poll.
  $courseObject = course_get_course_object('course_poll', 'poll', arg(1), $user);
  $courseObject->getFulfillment()->setComplete()->save();
}

/**
 * Implementation of hook_autoload_info().
 */
function course_poll_autoload_info() {
  return array(
    'CourseObjectPoll' => array(
      'file' => 'course_poll.classes.inc',
    ),
  );
}
