<?php

/**
 * Implements hook_node_info().
 */
function course_test_node_info() {
  return array(
    'course_test' => array(
      'name' => 'Course test',
      'module' => 'course_test',
      'description' => 'Course test content type',
    ),
  );
}

/**
 * Implements hook_course_handlers().
 */
function course_test_course_handlers() {
  return array(
    'object' => array(
      'course_test_object' => array(
        'name' => t('Test course object'),
        'class' => 'CourseObjectTest',
        'description' => t('A test course object.'),
      ),
    ),
  );
}

/**
 * Implements hook_install().
 */
function course_test_install() {
  variable_set('course_use_course_test', 1);
}
