<?php

/**
 * Implements hook_course_outline_completion_links_alter().
 *
 * Add a download certificate link.
 */
function course_certificate_course_outline_completion_links_alter(&$links, $node, $account) {
  if ($node->course['certificate'] == 1) {
    $links['certificate'] = array(
      'Download certificate',
      "node/$node->nid/certificate",
      'Download a PDF of your certificate.',
    );
  }
}
