<?php

/**
 * Implementation of hook_course_outline_completion_links_alter().
 *
 * Add a download certificate link.
 */
function course_certificate_course_outline_completion_links_alter(&$links, $node, $account) {
  if ($node->course['certificate'] == 1) {
    $links['certificate'] = array(
      'Download certificate',
      "node/$node->nid/certificate",
      'Download a PDF of your certificate.',
    );
  }
}

/**
 * Implementation of hook_access_certificate().
 *
 * If something entered a complete record into the reports table, return TRUE.
 */
function course_certificate_access_certificate($node, $user) {
  if (course_node_is_course($node)) {
    $sql = "select 1 from {course_report} where nid = %d and uid = %d and complete = %d";
    return (bool) $node->course['certificate'] && (bool) db_result(db_query($sql, $node->nid, $user->uid, 1));
  }
}

function course_certificate_token_list($type = 'all') {
  if ($type == 'certificate') {
    $tokens['certificate']["certificate-date_completed"] = t('Date of course completion');
    $tokens['certificate']['certificate-number'] = 'Generated certificate number';
    return $tokens;
  }
}

function course_certificate_token_values($type, $object = NULL, $options = array()) {
  if ($type == 'certificate') {
    $sql = 'select * from {course_report} where nid = %d and uid = %d';
    if ($report = db_fetch_object(db_query($sql, $object['node']->nid, $object['user']->uid))) {
      $values['certificate-date_completed'] = date(variable_get('course_report_certificate_time_format', 'F jS, Y'), $report->date_completed);
    }
    $values['certificate-number'] = time() . '-' . $object['node']->nid;
    return $values;
  }
}

/**
 * Implementation of hook_course_object_info().
 *
 * Expose certificate as a course object.
 */
function course_certificate_course_object_info() {
  return array(
    'certificate' => array(
      'title' => 'Certificate',
      'class' => 'CourseObjectCertificate',
    ),
  );
}
