<?php

/**
 * Implementation of hook_init().
 */
function course_webform_init() {
  $node = node_load(arg(1));
  if ($course = course_determine_context('course_webform', 'webform', $node->nid)) {
    course_set_context($course);
  }
}

/**
 * Implementation of hook_course_object_info().
 */
function course_webform_course_object_info() {
  return array(
    'webform' => array(
      'title' => 'Webform',
      'suggested title' => 'Evaluation',
      'class' => 'CourseObjectWebform',
      'description' => 'A webform to be used in a course workflow.',
      'graded' => FALSE,
    ),
  );
}

/**
 * Implementation of hook_webform_submission_insert().
 */
function course_webform_webform_submission_insert($node, $submission) {
  global $user;

  // Find the course object associated with this webform.
  $courseObject = course_get_course_object('course_webform', 'webform', arg(1), $user);
  $courseObject->getFulfillment()->setComplete()->save();
}
