<?php

function course_requirements_menu() {
  $items = array();

  $items['admin/settings/course/requirements'] = array(
    'page calback' => 'drupal_get_form',
    'page arguments' => array('course_requirements_settings_form'),
    'access arguments' => array('administer course'),
    'type' => MENU_LOCAL_TASK,
    'title' => 'Requirements',
  );

  return $items;
}

function course_requirements_settings_form() {
  $form = array();

  foreach (content_fields() as $field => $info) {
    if ($info['type'] == 'nodereference') {
      $fields[$field] = $field;
    }
  }

  $form['course_requirements_cck_field'] = array(
    '#type' => 'select',
    '#title' => 'Nodereference field used to select requirements',
    '#options' => $fields,
    '#default_value' => variable_get('course_requirements_cck_field', 'field_course_requirements'),
  );

  $form['course_requirements_allow_enrollments'] = array(
    '#title' => 'Allow enrollments',
    '#default_value' => variable_get('course_requirements_allow_enrollments', 0),
    '#description' => 'Allow enrollments into a blocked course. User is still prevented from taking the course.',
    '#type' => 'checkbox',
  );

  return system_settings_form($form);
}

function course_requirements_can_take_course($node, $user) {
  $field = variable_get('course_requirements_cck_field', 'field_course_requirements');
  if (isset($node->$field)) {
    $items = $node->$field;
    foreach ($items as $item) {
      $nids[] = $item['nid'];
    }
  }

  if (count($nids)) {
    $placeholders = db_placeholders($nids);
    $sql = "select * from {node} node
    left join {course_report} cr on cr.nid = node.nid and cr.uid = %d
    where node.nid in ($placeholders)";
    array_unshift($nids, $user->uid);
    $result = db_query($sql, $nids);
    while ($report = db_fetch_object($result)) {
      if (!$report->complete) {
        $block = TRUE;
      }
      $rows[] = array(l($report->title, "node/{$report->nid}"), $report->section_name);
    }
  }

  if ($block) {
    return array(
      array(
        'success' => FALSE,
        'header' => 'You must complete the following courses before taking this course.',
        'message' => theme('table', array('Course', 'Your Status'), $rows),
      ),
    );
  }
}

/**
 * Implements hook_course_can_enrol().
 */
function course_requirements_course_can_enrol($node, $user) {
  if (!variable_get('course_requirements_allow_enrollments', 0)) {
    $result = course_requirements_can_take_course($node, $user);
    if ($result[0]) {
      $result[0]['header'] = 'You must complete the following courses before enrolling in this course.';
      return $result;
    }
    elseif ($node->cr_parent) {
      $parent = node_load($node->cr_parent);
      return course_requirements_course_can_enrol($parent, $user);
    }
  }
}

/**
 * Implements hook_course_outline_completion_links_alter().
 */
function course_requirements_course_outline_completion_links_alter(&$links, $node, $user) {
  $field_name = variable_get('course_requirements_cck_field', 'field_course_requirements');
  $field = content_fields($field_name);
  $db_info = content_database_info($field);
  $sql = "select * from {{$db_info['table']}} t
  left join {node} n using (nid)
  where {$field_name}_nid = %d";
  $result = db_query($sql, $node->nid);
  while ($row = db_fetch_object($result)) {
    $courses[] = l($row->title, "node/$row->nid");
  }

  if ($courses) {

    $links['course_requirements'] = array(
      ' ',
      ' ',
      t('This course is a dependency of !courses', array('!courses' => implode(',', $courses))),
    );
  }
}
